// ================================================================
// Sentinel Protocol — North Architecture
// Copyright (c) 2026 North Architecture. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NorthArchitecture-SIL-1.0
// Original repo: github.com/NorthArchitecture/sentinel-engine
// Ranger Earn Build-A-Bear Hackathon 2025 — limited use.
// See LICENSE.md for full terms.
// ================================================================

/**
 * Demo script for judges (sentinel-ranger branch).
 *
 * Scenario:
 * 1. Initialize / derive a rail + ZK vault for the demo authority.
 * 2. Build a transparent SOL deposit instruction (`sentinel::deposit`).
 * 3. Build a confidential transfer instruction (`sentinel::confidential_transfer`).
 * 4. Build a transparent withdraw instruction (`sentinel::withdraw`).
 *
 * IMPORTANT:
 * - This script focuses on *building* and logging the full flow with clear,
 *   human-readable output. It does not broadcast transactions by default,
 *   because Groth16 proofs must be generated off-chain with the trusted
 *   setup artifacts before they can pass on-chain verification.
 * - Judges can inspect the logs to understand exactly how the vault behaves
 *   on devnet, and can wire in real Groth16 proofs to turn this into a live
 *   transaction flow.
 */

import * as anchor from "@coral-xyz/anchor";
import {
  type Program,
  type Idl,
} from "@coral-xyz/anchor";
import {
  PublicKey,
  SystemProgram,
  Transaction,
} from "@solana/web3.js";
import BN from "bn.js";

type SentinelIdlProgram = Program<Idl>;

interface DemoConfig {
  readonly clusterUrl: string;
  readonly walletPubkey: PublicKey;
}

const SENTINEL_PROGRAM_ID = new PublicKey(
  "C2WJzwp5XysqRm5PQuM6ZTAeYxxhRyUWf3UJnZjVqMV5",
);

/**
 * Deterministic PDAs for a single-rail, single-participant demo.
 *
 * For judges: these are the same seeds as in the on-chain program and tests.
 */
function deriveRailPda(authority: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("rail"), authority.toBuffer()],
    SENTINEL_PROGRAM_ID,
  )[0];
}

function deriveZkVaultPda(rail: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("zk_vault"), rail.toBuffer()],
    SENTINEL_PROGRAM_ID,
  )[0];
}

function deriveSolAssetStatePda(rail: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("asset_vault"), rail.toBuffer(), Buffer.from("sol")],
    SENTINEL_PROGRAM_ID,
  )[0];
}

function deriveVaultPoolPda(rail: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("vault_pool"), rail.toBuffer()],
    SENTINEL_PROGRAM_ID,
  )[0];
}

function deriveHandshakePda(rail: PublicKey, nullifier: Uint8Array): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("handshake"), rail.toBuffer(), Buffer.from(nullifier)],
    SENTINEL_PROGRAM_ID,
  )[0];
}

function deriveNullifierRegistryPda(
  rail: PublicKey,
  nullifier: Uint8Array,
): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("nullifier"), rail.toBuffer(), Buffer.from(nullifier)],
    SENTINEL_PROGRAM_ID,
  )[0];
}

function deriveDepositRecordPda(
  rail: PublicKey,
  sender: PublicKey,
  depositIndex: BN,
): PublicKey {
  const indexBuf = depositIndex.toArrayLike(Buffer, "le", 8) as Buffer;
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from("deposit"),
      rail.toBuffer(),
      sender.toBuffer(),
      indexBuf,
    ],
    SENTINEL_PROGRAM_ID,
  )[0];
}

async function withSentinelProgram(
  cfg: DemoConfig,
): Promise<SentinelIdlProgram> {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // In this repository, Sentinel is generated by Anchor with workspace name `Sentinel`.
  // We keep the type generic (Idl) to avoid depending on generated TS types.
  const program = (anchor.workspace
    .Sentinel as SentinelIdlProgram | undefined);
  if (!program) {
    throw new Error(
      "Sentinel program not found in anchor.workspace. Make sure Anchor.toml is configured and the IDL is built.",
    );
  }
  if (!program.programId.equals(SENTINEL_PROGRAM_ID)) {
    // Not fatal for the demo, but worth surfacing.
    console.warn(
      `[demo] Warning: Sentinel Program ID from workspace (${program.programId.toBase58()}) does not match demo constant (${SENTINEL_PROGRAM_ID.toBase58()}).`,
    );
  }
  console.log(
    `[demo] Connected to Sentinel at ${program.programId.toBase58()} on ${cfg.clusterUrl}`,
  );
  return program;
}

async function runDemo(): Promise<void> {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const cfg: DemoConfig = {
    clusterUrl: provider.connection.rpcEndpoint,
    walletPubkey: provider.wallet.publicKey,
  };

  console.log("==================================================");
  console.log(" Sentinel — Institutional ZK Privacy Vault (Demo) ");
  console.log("==================================================");
  console.log(`[demo] Cluster : ${cfg.clusterUrl}`);
  console.log(`[demo] Wallet  : ${cfg.walletPubkey.toBase58()}`);
  console.log("");

  const sentinel = await withSentinelProgram(cfg);

  // Step 1 — Derive rail + ZK vault PDAs
  console.log("1) Initializing rail + ZK vault (conceptual step)");
  const rail = deriveRailPda(cfg.walletPubkey);
  const zkVault = deriveZkVaultPda(rail);
  const solAssetState = deriveSolAssetStatePda(rail);
  const vaultPool = deriveVaultPoolPda(rail);

  console.log(`   - Rail PDA        : ${rail.toBase58()}`);
  console.log(`   - ZK vault PDA    : ${zkVault.toBase58()}`);
  console.log(`   - SOL asset state : ${solAssetState.toBase58()}`);
  console.log(`   - Vault pool PDA  : ${vaultPool.toBase58()}`);
  console.log(
    "   NOTE: In the full system, these accounts are created via `initialize_rail` and `initialize_zk_vault`.",
  );
  console.log("");

  // Common demo parameters (mock values, aligned with tests)
  const amountLamports = new BN(500_000); // 0.0005 SOL
  const dummyProof = Buffer.alloc(256, 1); // mock Groth16 proof bytes
  const commitmentBefore = Buffer.alloc(32, 11);
  const commitmentAfter = Buffer.alloc(32, 12);
  const receiverCommitmentBefore = Buffer.alloc(32, 13);
  const receiverCommitmentAfter = Buffer.alloc(32, 14);
  const nullifier = Buffer.alloc(32, 21);
  const encryptedBalanceBefore = Buffer.alloc(64, 44);
  const encryptedBalanceAfter = Buffer.alloc(64, 45);
  const receiverEncryptedBalanceAfter = Buffer.alloc(64, 46);

  // For the demo we assume this is the first deposit.
  const depositIndex = new BN(0);
  const depositRecord = deriveDepositRecordPda(
    rail,
    cfg.walletPubkey,
    depositIndex,
  );

  const handshake = deriveHandshakePda(rail, nullifier);
  const nullifierRegistry = deriveNullifierRegistryPda(rail, nullifier);

  // Step 2 — Transparent SOL deposit
  console.log("2) Transparent SOL deposit (Sentinel::deposit)");

  const depositIx = await sentinel.methods
    .deposit(
      amountLamports,
      dummyProof,
      Array.from(commitmentAfter),
      Array.from(nullifier),
      Array.from(encryptedBalanceAfter),
    )
    .accounts({
      rail,
      zkVault,
      solAssetState,
      handshake,
      vaultPool,
      depositRecord,
      sender: cfg.walletPubkey,
      authority: cfg.walletPubkey,
      systemProgram: SystemProgram.programId,
    })
    .instruction();

  console.log("   - Built `deposit` instruction (not sent).");
  console.log("   - From (sender)   :", cfg.walletPubkey.toBase58());
  console.log("   - To (vault pool) :", vaultPool.toBase58());
  console.log(
    "   - Amount (lamports):",
    amountLamports.toString(10),
  );
  console.log(
    "   NOTE: This instruction enforces a valid Groth16 proof on-chain; the `dummyProof` here is for structure only.",
  );
  console.log("");

  // Step 3 — Confidential ZK transfer (sender rail -> receiver rail)
  console.log("3) Confidential ZK transfer (Sentinel::confidential_transfer)");

  const receiverRail = rail; // demo: self-transfer along the same rail
  const receiverZkVault = zkVault;

  const transferNonce = new BN(1);

  const confidentialTransferIx = await sentinel.methods
    .confidentialTransfer(
      transferNonce,
      amountLamports,
      dummyProof,
      Array.from(commitmentBefore),
      Array.from(commitmentAfter),
      Array.from(receiverCommitmentBefore),
      Array.from(receiverCommitmentAfter),
      Array.from(nullifier),
      Array.from(encryptedBalanceAfter),
      Array.from(receiverEncryptedBalanceAfter),
    )
    .accounts({
      senderRail: rail,
      receiverRail,
      senderZkVault: zkVault,
      receiverZkVault,
      senderSolAssetState: solAssetState,
      receiverSolAssetState: solAssetState,
      senderVaultPool: vaultPool,
      receiverVaultPool: vaultPool,
      transferRecord: PublicKey.findProgramAddressSync(
        [
          Buffer.from("transfer"),
          rail.toBuffer(),
          receiverRail.toBuffer(),
          (() => {
          const buf = Buffer.alloc(8);
          // Use bn.js helper to write the nonce as little-endian 64-bit
          const tmp = transferNonce.toArrayLike(Buffer, "le", 8) as Buffer;
          tmp.copy(buf);
          return buf;
        })(),
        ],
        SENTINEL_PROGRAM_ID,
      )[0],
      authority: cfg.walletPubkey,
      receiverAuthority: cfg.walletPubkey,
      systemProgram: SystemProgram.programId,
    })
    .instruction();

  console.log("   - Built `confidential_transfer` instruction (not sent).");
  console.log("   - Sender rail   :", rail.toBase58());
  console.log("   - Receiver rail :", receiverRail.toBase58());
  console.log(
    "   - Amount (lamports):",
    amountLamports.toString(10),
  );
  console.log(
    "   NOTE: This step updates encrypted balances and commitments only; the amount and counterparties remain private.",
  );
  console.log("");

  // Step 4 — Transparent SOL withdraw
  console.log("4) Transparent SOL withdraw (Sentinel::withdraw)");

  const withdrawIx = await sentinel.methods
    .withdraw(
      amountLamports,
      dummyProof,
      Array.from(commitmentAfter),
      Array.from(commitmentBefore),
      Array.from(nullifier),
      Array.from(encryptedBalanceBefore),
    )
    .accounts({
      rail,
      zkVault,
      solAssetState,
      depositRecord,
      vaultPool,
      receiver: cfg.walletPubkey,
      authority: cfg.walletPubkey,
      systemProgram: SystemProgram.programId,
    })
    .instruction();

  console.log("   - Built `withdraw` instruction (not sent).");
  console.log("   - Receiver wallet :", cfg.walletPubkey.toBase58());
  console.log(
    "   - Amount (lamports):",
    amountLamports.toString(10),
  );
  console.log(
    "   NOTE: This step converts an encrypted balance back into a transparent SOL transfer for the receiver.",
  );
  console.log("");

  // Assemble a demo transaction (not sent)
  const tx = new Transaction().add(depositIx, confidentialTransferIx, withdrawIx);
  console.log("5) Assembled demo transaction (deposit → confidential_transfer → withdraw).");
  console.log("   - Instructions count:", tx.instructions.length);
  console.log("   - This transaction is NOT sent by default.");
  console.log(
    "   - To run it live, replace `dummyProof` and mock commitments with real Groth16 proofs and commitments generated off-chain.",
  );
  console.log("");

  console.log("Demo completed (structure only).");
}

void runDemo().catch((err) => {
  // eslint-disable-next-line no-console
  console.error("[demo] Fatal error:", err);
  process.exitCode = 1;
});

